# Generated by Django 2.2.13 on 2020-12-15 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(default=uuid.UUID('08846969-63af-41d5-8432-b23bdddedc6f'), max_length=255)),
                ('processed', models.TextField(default='0', max_length=255)),
                ('frames_processed', models.TextField(default='0', max_length=255)),
                ('frames_left', models.TextField(default='0', max_length=255)),
                ('frames_rate', models.TextField(default='0', max_length=255)),
                ('data', models.TextField(default='{}', max_length=255)),
                ('status', models.TextField(default='Unknown', max_length=255)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
